dist: trusty
language: java
sudo: true
services:
  - docker
jdk:
  - openjdk8

cache:
  directories:
    - ${HOME}/.m2

env:
  global:
    # This is the encrypted COVERITY_SCAN_TOKEN, created via the
    # `travis encrypt` command using the project repo's public key.
    - secure: "v5ixqTeb74y0vRuPcDbe3C28GDDYvqyEXA2dt+9UVU6GG7WpnmpkBf05gI1dIhp51lBhwx9WSlFBtzho+KdCBmNY/CzBRhVHe/lCQYK9Hb6uGPvuwBvC0WjJgJXsVrLFjppeRhcf+OAweVQ3uw2RPMDRvKIVMUcO1BTFjjJl6REJXNUdzGS57MtH2mmRyOEz250EwgqUELZvcOytG7fNrjMJKVK2nSsoxi0BqZIpItTWPWWeQ1wi1FplJ18A2qtD+MPfAGNSB+/a+r0Av+VCT2eGl06ZyZAzP3q/vG5IYjQ3AJsSPqcZUt4ms+2us1+kwuzXIILjzZmcfImu29+y/thndU5E5b2v+nZ4H69CUCc5OmKW2RwozLNmBIUhO0n+35va/J7FiPIqm3pwxCz5vWA3YTHDADxnIYe7+9uY/+dOK/AvP5fyu7u07vuF3liKNBdrX7ylP3kYc7FXGmYl8wCZv31iy1yTtndQ9qKef7bo8lM9Cdh39KyowrygH+Um7pr9gqf2S9jn99nQ3bib32fBWgBkLpJRwhZYHPUupZjZfgu/9woby0DuriuHZKMqZd7QUawYz6wXGlhzu78x5Tohlj1pGBwHYdcJ/Tm3PiEpyH4aYQLffkjGHJAcCW5tO8QbB0qrLYWC8xVMWuFz1TpSBRXOqVYdBfIa2UZDtOU="
    - COVERITY_BRANCH_NAME="coverity_scan"
    - COVERITY_EMAIL="sjudeng@gmail.com"
    # Default Elasticsearch heap size can be too large for Travis
    - ES_JAVA_OPTS="-Xms256m -Xmx512m"

  matrix:
    - COVERITY_ONLY=true

install:
  - echo "Skipping module build on Coverity branch/job";

script:
  - docker build -t janusgraph/analysis analysis;
  - docker run --rm \
      -v "${HOME}/.m2:/root/.m2" \
      -v "${PWD}:/opt/janusgraph" \
      -i janusgraph/analysis;
  - file test.test

