dist: trusty
language: java
sudo: true
services:
  - docker
jdk:
  - openjdk8

cache:
  directories:
    - ${HOME}/.m2

env:
  matrix:
    - MODULE='cassandra' CASSANDRA_VERSION='3.11.0' ARGS='-Dtest=**/thrift/* -Dtest.skip.ordered=true -Dtest.skip.ssl=true'
    - MODULE='cassandra' CASSANDRA_VERSION='3.11.0' ARGS='-Dtest=**/astyanax/* -Dtest.skip.ordered=true -Dtest.skip.ssl=true'
    - MODULE='cql' CASSANDRA_VERSION='3.11.0' ARGS='-Dtest.skip.byteorderedpartitioner=true -Dtest.skip.murmur-ssl=true'

    - MODULE='cassandra' CASSANDRA_VERSION='3.0.14' ARGS='-Dtest=**/thrift/* -Dtest.skip.ordered=true -Dtest.skip.ssl=true'
    - MODULE='cassandra' CASSANDRA_VERSION='3.0.14' ARGS='-Dtest=**/astyanax/* -Dtest.skip.ordered=true -Dtest.skip.ssl=true'
    - MODULE='cql' CASSANDRA_VERSION='3.0.14' ARGS='-Dtest.skip.byteorderedpartitioner=true -Dtest.skip.murmur-ssl=true'

    - MODULE='cassandra' CASSANDRA_VERSION='2.2.10' ARGS='-Dtest=**/thrift/* -Dtest.skip.ordered=true -Dtest.skip.ssl=true'
    - MODULE='cassandra' CASSANDRA_VERSION='2.2.10' ARGS='-Dtest=**/astyanax/* -Dtest.skip.ordered=true -Dtest.skip.ssl=true'
    - MODULE='cql' CASSANDRA_VERSION='2.2.10' ARGS='-Dtest.skip.byteorderedpartitioner=true -Dtest.skip.murmur-ssl=true'

before_install:
  - docker-compose -f janusgraph-cassandra/src/test/resources/docker-compose.yml up -d
  - until docker exec -it jg-cassandra sh -c 'exec cqlsh -e "show host"' || docker exec -it jg-cassandra sh -c 'exec cqlsh --ssl -e "show host"'; do
      >&2 echo "Cassandra is unavailable - sleeping";
      docker-compose -f janusgraph-cassandra/src/test/resources/docker-compose.yml logs;
      sleep 1;
    done
  - echo "Cassandra is up"
  - sleep 5

install:
  - travis_retry travis_wait \
        mvn install --projects janusgraph-${MODULE} --also-make \
          -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version;

script:
  - travis_retry travis_wait 50 \
        mvn clean verify --projects janusgraph-${MODULE} \
          -Dstorage.hostname=`docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' jg-cassandra` \
          ${ARGS};

# Syntax and more info: https://docs.travis-ci.com/user/notifications
notifications:
  email:
    - janusgraph-ci@googlegroups.com
