dist: trusty
language: java
sudo: true
services:
  - docker
jdk:
  - openjdk8

cache:
  directories:
    - ${HOME}/.m2

env:
  matrix:
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/diskstorage/hbase/* -Dhbase100.core.version=1.1.11'
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/diskstorage/hbase/* -Dhbase100.core.version=1.1.10'
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/diskstorage/hbase/* -Dhbase100.core.version=1.1.9'
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/diskstorage/hbase/* -Dhbase100.core.version=1.1.8'
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/diskstorage/hbase/* -Dhbase100.core.version=1.1.7'
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/diskstorage/hbase/* -Dhbase100.core.version=1.1.6'
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/diskstorage/hbase/* -Dhbase100.core.version=1.1.5'
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/diskstorage/hbase/* -Dhbase100.core.version=1.1.4'
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/diskstorage/hbase/* -Dhbase100.core.version=1.1.3'
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/diskstorage/hbase/* -Dhbase100.core.version=1.1.2'
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/diskstorage/hbase/* -Dhbase100.core.version=1.1.1'
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/diskstorage/hbase/* -Dhbase100.core.version=1.1.0'
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/graphdb/hbase/* -Dhbase100.core.version=1.1.11'
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/graphdb/hbase/* -Dhbase100.core.version=1.1.10'
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/graphdb/hbase/* -Dhbase100.core.version=1.1.9'
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/graphdb/hbase/* -Dhbase100.core.version=1.1.8'
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/graphdb/hbase/* -Dhbase100.core.version=1.1.7'
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/graphdb/hbase/* -Dhbase100.core.version=1.1.6'
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/graphdb/hbase/* -Dhbase100.core.version=1.1.5'
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/graphdb/hbase/* -Dhbase100.core.version=1.1.4'
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/graphdb/hbase/* -Dhbase100.core.version=1.1.3'
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/graphdb/hbase/* -Dhbase100.core.version=1.1.2'
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/graphdb/hbase/* -Dhbase100.core.version=1.1.1'
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/graphdb/hbase/* -Dhbase100.core.version=1.1.0'

install:
  - travis_retry travis_wait \
      mvn install --projects janusgraph-${MODULE} --also-make \
      -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version;

script:
  - travis_retry travis_wait 50 \
     mvn clean verify --projects janusgraph-${MODULE} -Pcoverage ${ARGS};

# Syntax and more info: https://docs.travis-ci.com/user/notifications
notifications:
  email:
    - janusgraph-ci@googlegroups.com
