dist: trusty
language: java
sudo: true
services:
  - docker
jdk:
  - openjdk8

cache:
  directories:
    - ${HOME}/.m2

env:
  matrix:
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/diskstorage/hbase/* -Dhbase100.core.version=1.3.1'
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/graphdb/hbase/* -Dhbase100.core.version=1.3.1'
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/diskstorage/hbase/* -Dhbase100.core.version=1.1.12'
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/graphdb/hbase/* -Dhbase100.core.version=1.1.12'
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/diskstorage/hbase/* -Dhbase100.core.version=1.0.3'
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/graphdb/hbase/* -Dhbase100.core.version=1.0.3'
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/diskstorage/hbase/*'
    - MODULE='hbase-parent/janusgraph-hbase-10' ARGS='-Dtest=**/graphdb/hbase/*'
    - MODULE='hbase-parent/janusgraph-hbase-098' ARGS='-Dtest=**/diskstorage/hbase/*'
    - MODULE='hbase-parent/janusgraph-hbase-098' ARGS='-Dtest=**/graphdb/hbase/*'

install:
  - travis_retry travis_wait \
      mvn install --projects janusgraph-${MODULE} --also-make \
      -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version;

script:
  - travis_retry travis_wait 50 \
     mvn clean verify --projects janusgraph-${MODULE} -Pcoverage ${ARGS};

# Syntax and more info: https://docs.travis-ci.com/user/notifications
notifications:
  email:
    - janusgraph-ci@googlegroups.com
